### ISSUE TITLE
Resource not found: human_description while running robot_amcl.launch 

### ISSUE THREAD

**Issue by 2000222** [MalayNagda/ROS_Gazebo#1]
Hi, this is really a good repository. But I faced the following problems while running
`roslaunch pursuit_evasion robot_amcl.launch map_file:=/home/tbml_ws/src/turtlebot3/turtlebot3_navigation/maps/map.yaml world_index:=0
... logging to /home/sarah/.ros/log/b292b844-758d-11eb-a27b-3024323c9f88/roslaunch-sarah-TUF-GAMING-FX504GM-FX80GM-12201.log
Checking log directory for disk usage. This may take a while.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

xacro: in-order processing became default in ROS Melodic. You can drop the option.
Resource not found: human_description
ROS path [0]=/opt/ros/melodic/share/ros
ROS path [1]=/home/sarah/tbml_ws/src
ROS path [2]=/opt/ros/melodic/share
The traceback for the exception was written to the log file`

Maybe I guess could u share us with the "human_description" directory?
Thanks a lot.

**Comment by MalayNagda** [comment]
Hi. glad you liked it. I have added the 'human description' directory to this repo. Just acknowledge Dr. Yezhou Yang and Duo Lu when citing as both of them were instructors for the course and provided the resources. 

Malay.
